### ISSUE TITLE
websorket 连接报错  返回400错误

### ISSUE THREAD

**Issue by lpc0217** [gzydong/hyperf-chat#3]
其他服务都已正常 
websorket 连接报错  返回400错误
服务端报错提示：[WARNING] WebSocket hande shake failed, because the class does not exists.
9504端口能打开 但是 浏览器访问 返回400
请问大神 这个问题如何解决  java党 对php不是很熟悉

**Comment by gzydong** [comment]
Jwt 验证失败，所以握手不成功
